### ISSUE TITLE
Getting started example only displays a blank page

### ISSUE THREAD

**Issue by pmatsinopoulos** [lukeed/bee3d#13]
I am trying to run the example that comes in the Getting Started page. And I only see a blank page.

**Comment by lukeed** [comment]
It needs CSS 

I strongly suggest you start with one of the example files, like `basic.html`. All of those work and have everything you need. They will probably answer a lot of your questions too

**Comment by pmatsinopoulos** [comment]
What do you mean it needs CSS. The source code I am using is exactly the one you have in you Getting Started Wiki page. Does that code work or not? I have built the project exactly as you have it your Getting Started page and it only shows a blank page. Does it work for you?

**Comment by lukeed** [comment]
It needs styling.

Yes, it works. `Getting Started` is for people who want to understand concepts as opposed to just copy & pasting. You want to copy & paste---that's fine!, but that's why there are 30+ example files for you to choose from.

The `Getting Started` code will provide you with a "blank page", but it's actually working. For example, if I add this CSS code to the page:

``` css
#demo {
    margin-top: 300px;
}
.bee3D--slide {
    background-color: gray;
}
```

You will now see everything.

Then you would need to add more Bee3D options so that you can navigate. For example, you may do something like this now:

``` javascript
  var demo = document.getElementById('demo');

  var slider = new Bee3D(demo, {
    effect: 'concave',
    listeners: {
      keys: true
    }
    // ... more options here
  });
```

... and so on. Bee3D is HIGHLY customizable & was built to be that way.

So if you're feeling lost or overwhelmed, please start from one of the example files. That's why I made them.

**Comment by pmatsinopoulos** [comment]
I suppose that if you had this short answer that you gave me above in your Getting Started page (which was obsolete in the first place) I wouldn't have bother you with my issues and questions here. I am not the person who likes to copy & paste, but I need to understand the API in order to use it. For example, in your documentation you do not say which classes can  / need to be used (am I wrong?) Look at the documentation of your competitor here: http://www.masterslider.com/doc in order to understand the difference of documentation quality.

You can consider this issue closed and thank you very much for the detailed explanation above.

**Comment by pmatsinopoulos** [comment]
BTW...My suggestion here is that you add a note (inside your Getting Started wiki page) for somebody to look into the examples in the "build/examples" folder of the downloaded/purchased package. It was completely missed because while reading the documentation on Github and trying to build the examples mentioned there, didn't have an idea that there was an `examples` folder in the purchased package.

IMHO...the two improvements I am mentioning in the issue here, will save you in the future from having to answer similar questions to the ones that I asked.

**Comment by lukeed** [comment]
I'll add this to the docs then, thanks!

I don't mind questions or issues at all! So not a "bother" by any means

> For example, in your documentation you do not say which classes can / need to be used (am I wrong?) 

Check [this](https://github.com/lukeed/bee3d/wiki/Options) out. 

You don't need to use any classes, you just have to specify what the slide selector is. So, if all your slides started with `<section>` tags, then your `selector` option can be: `selector: 'section'`.

All other Bee3D classes will be applied automatically once you've initialized Bee3D onto an element.

_Note: A 'bee3D--slide' class will still be added to all your slides even if you customize the `selector`. This is so that the necessary styles will be inherited._

**Re: MasterSlider**
Thanks. I've been through these docs before & they've developed & improved over time, as will these :smiley: 

Mine are a little more concise, for better or for worse. And they have a _true_ beginner's guide, that sets you up with a CSS skin. Bee3D (version1) had that, but more people hated it than liked it.

**Comment by lukeed** [comment]
Updated [Getting Started](https://github.com/lukeed/bee3d/wiki/Getting-Started)
