### ISSUE TITLE
Listeners Keys Controlling Two Different Slider

### ISSUE THREAD

**Issue by weehong-1** [lukeed/bee3d#16]
Hi.

I am here to seek for help to solve an issue regarding to the keys listeners is controlling two different slider.

Is that possible to assign every single of the slider has their own key listeners?

And is that possible to created two different **bee3D--nav__next** to control different slider?

Like  **bee3D--nav__next-1** and  **bee3D--nav__next-2**

**Comment by lukeed** [comment]
Hey,

You **can** have multiple sliders listen to the keyboard keys, but they will all share the same event. Eg, pressing the `RIGHT` arrow-key will have both sliders go to the next slide.

You **can't** have sliders have key listeners sometimes but not others. Eg, pressing `RIGHT` will always be heard by both sliders. You can't make a slider stop listening on command.

You **could** have a slider listen to certain keys and another listen to different keys. You would have to write you own plugin for that though since it's not part of the plugin. For example:

``` javascript
var slider1 = new Bee3D(...)
var slider2 = new Bee3D(...)

document.addEventListener('keyup', function(e){
  // slider1: A & D
  if (e.which == 65) slider1.el.prev();
  if (e.which == 68) slider1.el.next();
  // slider2: Q & E
  if (e.which == 81) slider2.el.prev();
  if (e.which == 69) slider2.el.next();
})
```

You **can** have multiple navigation arrows on a page. You just have to embed them within the slider parent. For example:

``` html
<article class="parent-1">
    <section class="slide"></section>
    <section class="slide"></section>
    <section class="slide"></section>

    <span class="bee3D--nav bee3D--nav__prev"></span>
    <span class="bee3D--nav bee3D--nav__next"></span>
</article>

<article class="parent-2">
    <section class="slide"></section>
    <section class="slide"></section>
    <section class="slide"></section>

    <span class="bee3D--nav bee3D--nav__prev"></span>
    <span class="bee3D--nav bee3D--nav__next"></span>
</article>
```

The sliders' parents (`article`) looks for its own `bee3D--nav__next` or `bee3D--nav__prev` child elements.
