### ISSUE TITLE
Responsiveness of sliders

### ISSUE THREAD

**Issue by nux17** [lukeed/bee3d#28]
Currently working on a mobile app, I can't manage to make the sliders responsive in size.
I want them to be resized when the viewport width reduces... How can I do that?

**Comment by lukeed** [comment]
You have to set your new styles (and pertaining breakpoints) with CSS. You have a number of options.
1. If you're comfortable using `zoom` you can use that directly on each `.bee3d--slide` element. 
2. You can apply a `transform: scale(0.x)` to the `.bee3D--parent` element. (This is easiest).
3. You can manually set each `slide`'s new width & height
4. If you have a content wrapper around each slide's inner content, you can apply `transform: scale()` to that selector.

**Comment by nux17** [comment]
Thanks for the answer!

Is there a way to reduce the spacing between two slides?
I'm using the 'concave' effect, and want the slides to be more visible by reducing the space between them.

**Comment by lukeed** [comment]
Hey nux, no problem.

Yes you can edit the spacings. Again with CSS, open to `src/styles/_basic.sass` and in the base `$slide-class` selector, you'll find:

``` sass
// slide spacing
margin-left: -$slide-w/2
margin-top: -$slide-h/2
```

Adjust those margins to your liking. Note that `-$slide-w/2` is the same as `-50%`, so you can increase that number for less space between. Also keep in mind that `top` and `left` interact with your new margins, but those shouldn't be adjusted unless you really know what you're doing.

Closing since the original issue was resolved. :)
