### ISSUE TITLE
Parallax

### ISSUE THREAD

**Issue by mthorlund** [lukeed/bee3d#31]
Hey
When I try to initialize parallaxing effect I get an error and the slider breaks:
Uncaught TypeError: Cannot read property 'classList' of null 

I narrowed it down to this part of the code in bee3D.js

``` javascript
// edited
var u = e[l];
a(u.firstElementChild), i && a(u.lastChild)
```

My slide html looks like this:

```
<div id="demo" class="bee3D--parent">
    <section class="bee3D--slide"></section>
    <section class="bee3D--slide">Slide 2</section>
    <section class="bee3D--slide">Slide 3</section>
    <section class="bee3D--slide">Slide 4</section>
    <section class="bee3D--slide">Slide 5</section>
    <section class="bee3D--slide">Slide 6</section>
    <section class="bee3D--slide">Slide 7</section>
</div>
```

And my init js:

``` javascript
var demo = document.getElementById('demo');

        var slider = new Bee3D(demo, {
            effect: 'coverflow--vertical',
            listeners: {
                keys: true,
                clicks: true
            },
            focus: 6,
            navigation: {
                enabled: true
            },
            parallax: {
                enabled: true
            }
        });
```

**Comment by larsmunkholm** [comment]
I'm having this issue as well. Any help?

**Comment by lukeed** [comment]
Inside the Parallax loop, you see this:

``` js
a(u.firstElementChild)
```

... That's the minified version, but `a` is `applyParallaxTo` in the non-minified (`src/javascript/features/parallax/index.js`). It is here that a `className` is added.

What's happening is that the initializer is expecting a Node within each slide. I believe I did this because the CSS wasn't 100% compatible on browsers if everything was all on the same element. 

To fix, you can either:
- Add an inner div to each slide.
  
  ``` html
  <div class="bee3D--slide">
      <div class="bee3D--inner">Slide #</dv>
  </div>
  ```
- Or remove the `firstElementChild` from the Parallax script. I can't guarantee this will work everywhere.

---

Editing your post to remove the JS code block. 🙈

**Comment by larsmunkholm** [comment]
Thanks @lukeed :)
That fixed the error, but the parallax-effect still didn't work, so I messed around with parallax.js a bit and found that the variable "y" in setPosition() was NaN.
Apparently I needed to **set a height for bee3D--parent**. Maybe this could be more apparent in the [documentation](https://github.com/lukeed/bee3d/wiki/Getting-Started#customizing) :)

**Comment by lukeed** [comment]
@uhlalars Ah, I didn't actually know that. My demos, testing, and use-cases always had fixed heights on the slides themselves & an absolutely positioned `.bee3D--parent` that touched all corners of the screen:

``` sass
.bee3D--parent
  position: absolute
  bottom: 0
  top: 0
  right: 0
  left: 0
```

This, in effect, was the same as setting a height.

---

Closing since the issue/question has been resolved. 👍
