### ISSUE TITLE
How can I use it with jquery and bootstrap?

### ISSUE THREAD

**Issue by ozumemre** [lukeed/bee3d#39]
How can I use it with jquery and bootstrap css, js?
Slider doesn't run When I added these.
Can you help me, please
Thanks

**Comment by lukeed** [comment]
Hi @ozumemre 

Bootstrap doesn't affect Bee3D in anyway. It's just CSS styling. jQuery works with it too; you just can't have jQuery interacting with the Bee3D markup or JS.

You will have to send me your code so that I can actually take a look. It's definitely possible; something is just wrong right now.

**Comment by ozumemre** [comment]
Hello
thank you for your response.
It is my mistake.
I have resolved the problem.
Thank you very much

**Comment by lukeed** [comment]
Great! Glad to hear you got it fixed! :)

Good luck~
