### ISSUE TITLE
How can I start the slider

### ISSUE THREAD

**Issue by aparrap21** [lukeed/bee3d#66]
Hi, recently i bought the Bee3d Slider, im not a developer expert but i have knowlenges about code implementation.

I have a question.

¿How can i start the slider? I already saw many post about this but I think I need some help. The example files doesnt work properly or i have to do something aditional.

There are an adittional steps that i have to do?

Thanks for the support.

**Comment by lukeed** [comment]
Hi there~! Thanks for your purchase 🙏 

Have you see this [Development](https://github.com/lukeed/bee3d/wiki/Development) page yet? It's linked to from within the ZIP contents.

You need to have Node.js installed, and then `npm install` so that all the build tools are installed. Then running `npm run watch` let you edit the files as needed in a dev server, and `npm run build` will build the minified files once you're done.

If you'd rather, I can just upload the pre-built files here.

**Comment by aparrap21** [comment]
Hi, I´ll be awesome if u can send me a pre-built file.

Thanks

**Comment by lukeed** [comment]
Here here you go~! [dist.zip](https://github.com/lukeed/bee3d/files/1797312/dist-updated.zip)
