### ISSUE TITLE
I keep getting this error when I finish npm install :(

### ISSUE THREAD

**Issue by eltongreenfield** [lukeed/bee3d#76]
Hello I purchased your plugin hoping to finally achieve something like[ this product carousel ](https://shop.theweeknd.com/)by using your concave slider code. I am very new to programming and I was able to successfully download Node.js on Mac OS. But once it came to installing the dependencies, I started running into issues. 
<img width="1278" alt="Screen Shot 2020-07-15 at 3 58 11 AM" src="https://user-images.githubusercontent.com/42484501/87537594-ac151400-c64f-11ea-8bf5-bf93cfa9d205.png"> I would love to know how to bypass this error so that I can get to building asap, thank you so much!

**Comment by lukeed** [comment]
Hey, thank you!

Your `npm install` failed -- that's why your `npm run watch` doesn't work (and never will). I'd try rerunning `npm install` to finish gathering the dependencies. If that fails then you may have a permissions issue with `npm` on your system.

In any event, you may not need to do this at all. There's an included "dist" directory in your extracted ZIP -- it will contain all the pre-built files for you.

Hope that helps!

**Comment by lukeed** [comment]
Oh I see the issue.

Installation failed because `got` set a version cap on `node` (which is odd) and since `npm` wants to be strict, it bails the install.

If you still want to install the build tools (unlikely in most cases) you can [install `yarn`](https://classic.yarnpkg.com/en/docs/install#debian-stable) and then run:

```sh
$ yarn install --ignore-engines
```

As the name suggests, that will ignore all version constraints. 👍

**Comment by eltongreenfield** [comment]
Hey Luke,

I appreciate the timely response! Okay so if I were use the “dist” folder
with the compiled CSS, how would that work? I’m a little confused on the
process of implementing the plugin within a new html file. I looked over
your notes about Getting Started but it’s not clicking with me yet. I
attempted to link the examples you provided with the css included and it
isn’t yielding any results in terms of styling. If you could break that
down for me that would be great!

Thanks a ton for your help,
Elton

**Comment by lukeed** [comment]
Hey, have you seen #75 ?

The general idea is that you want to place the `/dist` contents into locations that you want & then it's just a matter of attaching `link` and `script` tags that point to those locations. Beyond that, you're looking to configure/use Bee3D as the rest of the Wiki/documentation describes.

**Comment by eltongreenfield** [comment]
Okay I’ll give it a try. I’ll let you know if there are any more issues but
otherwise I think I’ll be good to go.

Thanks again,
Elton
