### ISSUE TITLE
Concave effect, how to set number of visible sliders?

### ISSUE THREAD

**Issue by anthonylan** [lukeed/bee3d#78]
Hi Lukeed, so I actually bought this plugin because of the concave effect. by default only 3 sliders are visible, but I'd like to make 4 or 5 sliders to be visible. please how can it be done?

**Comment by lukeed** [comment]
Hi there,

Unfortunately, `concave` is only _meant_ to display 3 slides at a time. And there's no JS option to easily change this.

All effects are completely controlled through CSS transformations. This is what makes Bee3D so performant.
In `concave` effect, this also includes how many slides are visible (via translation + scale + rotation). 

So you'll have to manually:

* modify `.bee3D--effect__concave .bee3D--after-1` and `.bee3D--effect__concave .bee3D--before-1` classes so that they're smaller (scaled down) and/or rotated less

* add new `.bee3D--effect__concave .bee3D--before-2` and `.bee3D--effect__concave .bee3D--after-2` classes that look nice next to your new `(before|after)-1` appearance

* (probably) modify the `.bee3D--after` and `.bee3D--before` classes so that slides transition off screen smoothly, following your new rotation curve

While not the same thing, you can look at a [previous answer](https://github.com/lukeed/bee3d/issues/32#issuecomment-246803955) as an additional guideline for your customizations :) 

One thing to remember is that you only have to calculate one set of transformations! The `before` and `after` classes are inverses of each other. Once you're happy with one half, just go from positive to negative for translations, and then offset from 0 or 360 for rotations.

Hope that helps!

**Comment by anthonylan** [comment]
Thanks a lot, Lukeed, it worked!
