### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by ajha-aapna** [lukeed/bee3d#84]
Hi,
I was confused with the title on the codecanyon- Pure JS.

I need to use this plugin on the WordPress website but found that the files are not in HTML5/Pure Javascript/jQuery version hence I am facing the issue to incorporate them with the WordPress website.

It would be great if you provide a plain javascript/HTML5 version.

**Comment by lukeed** [comment]
It is plain JS/HTML, it just includes build tools so that you can more easily customize it as needed.

There are instructions included for getting everything situated. There's also a `dist` directory in the download that has all the files pre-built and ready to go, if you don't want to deal with build tools.

Hope that helps.
